routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\MyPostController;
use App\Http\Controllers\BookmarkController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/page/terms', [PageController::class, 'terms'])->name('page.terms');
Route::get('/page/policy', [PageController::class, 'policy'])->name('page.policy');
Route::get('/page/contact', [PageController::class, 'contact'])->name('page.contact');

Route::middleware('auth')->group(function () {
    Route::resource('/posts', PostController::class)->except('index');
    Route::get('/myposts', [MyPostController::class, 'index'])->name('myposts.index');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::delete('/posts/{post}/unbookmark', [BookmarkController::class, 'destroy'])->name('bookmarks.destroy');
    Route::post('/posts/{post}/bookmark', [BookmarkController::class, 'store'])->name('bookmarks.store');
    Route::get('/bookmarks', [PostController::class, 'bookmark_posts'])->name('bookmarks');
});

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');
Route::resource('/users', UserController::class)->only(['index', 'show']);

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

        /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'title',
        'description',
        'level',
        'user_id',
        'file_name',
        'file_mimetype',
        'file_size',
        'text_id',
    ];

    protected $appends = ['file_url'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function text()
    {
        return $this->belongsTo(Text::class);
    }

    // アップロードされた教案ファイルのアクセサ
    public function getFileUrlAttribute()
    {
        return \Storage::url('public/files/' . $this->file_name);
    }

    // マークダウンをパースする
    public function getDescriptionMarkdownAttribute()
    {
        return \Str::markdown(e($this->description));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Text;
use Illuminate\Http\Request;
use App\Http\Requests\StorePostRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     * @param Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // 検索フォームに入力された値を取得
        $keyword = $request->keyword;
        $text_id = $request->text_id;
        $level = $request->level;

        $query = Post::latest();

        // キーワードで検索をしたときだけ実行
        if ($keyword)
        {
            $word = '%' . $keyword . '%';
            $query->where(function ($q) use ($word)
            {
                $q->where('title', 'like', $word);
                $q->orWhere('description', 'like', $word);
                $q->orWhereHas('user', function ($u) use ($word)
                {
                    $u->where('name', 'like', $word);
                });
            });
        }

        // 使用テキストの検索があったとき実行
        if ($text_id)
        {
            $query->where('text_id', $text_id);
        }

        // レベルの検索があったとき実行
        if ($level)
        {
            $query->where('level', $level);
        }

        $posts = $query->paginate(15);
        $data = ['posts' => $posts];

        return view('posts.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = new Post();
        $data = ['post' => $post];

        return view('posts.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param App\Http\Requests\StorePostRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        $validated = $request->validated();

        $post = new Post();
        $post->title = $validated['title'];
        $post->description = $validated['description'];
        $post->level = $validated['level'];
        $post->user_id = \Auth::id();
        $post->text_id = $validated['text_id'];

        if (isset($validated['file_name']))
        {
            $file = $validated['file_name'];
            $ext  = $file->getClientOriginalextension();

            // ファイルをストレージへ保存
            $fileName = time() . '.' . $ext;
            $file->storeAs('public/files', $fileName);

            $post->file_name = $fileName;
            $post->file_mimetype = $file->getMimeType();
            $post->file_size = $file->getSize();
        }
        $post->save();

        return redirect(route('myposts.index'))->with('successMessage', '教案を投稿しました。');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        if (isset($post->file_size))
        {
            $kilobyte = 1024; // 1KB
            $megabyte = $kilobyte * 1000; // 1MB

            // アップロードファイルのサイズをメガバイト、キロバイトへ変換
            if ($megabyte <= $post->file_size)
            {
                // メガバイトへ変換、小数点2桁より下の桁は四捨五入
                $post->file_size = round($post->file_size / $megabyte, 2) . 'MB';
            } elseif ($kilobyte <= $post->file_size)
            {
                // キロバイトへ変換、小数点2桁より下の桁は四捨五入
                $post->file_size = round($post->file_size / $kilobyte, 2) . 'KB';
            } else
            {
                $post->file_size = $post->file_size . 'B';
            }
        }

        $data = ['post' => $post];
        return view('posts.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $this->authorize($post);

        $data = ['post' => $post];
        return view('posts.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param App\Http\Requests\StorePostRequest $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(StorePostRequest $request, Post $post)
    {
        $this->authorize($post);
        $validated = $request->validated();

        // ファイルの差し替えを行う
        if (isset($validated['file_name']))
        {
            // 元ファイルの削除
            \Storage::delete('public/files/' . $post->file_name);

            // 新ファイルの保存
            $file = $validated['file_name'];
            $ext  = $file->getClientOriginalextension();
            $fileName = time() . '.' . $ext;
            $file->storeAs('public/files', $fileName);

            // 新ファイルのデータをpostsテーブルの各カラムに保存
            $post->file_name = $fileName;
            $post->file_mimetype = $file->getMimeType();
            $post->file_size = $file->getSize();
        }

        $post->title = $validated['title'];
        $post->description = $validated['description'];
        $post->level = $validated['level'];
        $post->text_id = $validated['text_id'];
        $post->save();

        return redirect(route('posts.show', $post))->with('successMessage', '教案を更新しました。');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $this->authorize($post);
        $post->delete();
        // アップロードされたファイルの削除
        \Storage::delete('public/files/' . $post->file_name);

        return redirect(route('myposts.index'))->with('successMessage', '教案を削除しました。');

    }

    /**
     * Display a listing of the resource.
     *
     * ブックマークした教案を表示する
     * @return \Illuminate\Http\Response
     */
    public function bookmark_posts()
    {
        $posts = \Auth::user()->bookmark_posts()->latest()->paginate(15);
        $data = ['posts' => $posts];

        return view('posts.bookmarks', $data);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/posts/bookmarks.blade.php
<x-app-layout>
    <x-slot name="header">ブックマーク一覧</x-slot>
    <x-slot name="title">ブックマーク一覧</x-slot>
    <x-index-cards :posts="$posts" message="まだブックマークしていません。" />
</x-app-layout>

resources/views/posts/create.blade.php
<x-app-layout>
    <x-slot name="header">投稿フォーム</x-slot>
    <x-slot name="title">教案投稿フォーム</x-slot>
    <div class="w-full max-w-2xl mx-auto">
        <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
            <x-form :texts="$texts" :post="$post" />
            <div class="flex justify-center py-5">
                <x-primary-button type="submit" class="mr-12 bg-orange-400 shadow-md hover:bg-orange-300 active:bg-orange-400 focus:bg-orange-400">投稿する</x-primary-button>
                <x-secondary-button onclick="location.href='{{ route('myposts.index') }}'">キャンセル</x-secondary-button>
            </div>
        </form>
    </div>
</x-app-layout>

resources/views/posts/edit.blade.php
<x-app-layout>
    <x-slot name="header">編集フォーム</x-slot>
    <x-slot name="title">教案編集フォーム</x-slot>
    <div class="w-full max-w-2xl mx-auto">
        <form action="{{ route('posts.update', $post) }}" method="POST" enctype="multipart/form-data">
            @method('PATCH')
            <x-form :texts="$texts" :post="$post" />
            <div class="flex justify-center py-5">
                <x-primary-button type="submit" class="mr-12 bg-orange-400 shadow-md hover:bg-orange-300 active:bg-orange-400 focus:bg-orange-400">更新する</x-primary-button>
                <x-secondary-button onclick="location.href='{{ route('posts.show', $post) }}'">キャンセル</x-secondary-button>
            </div>
        </form>
    </div>
</x-app-layout>

resources/views/posts/index.blade.php
<x-app-layout>
    <x-slot name="header">みんなの教案一覧</x-slot>
    <x-slot name="title">みんなの教案</x-slot>
    <x-index-cards :posts="$posts" message="教案がありません。"/>
</x-app-layout>

resources/views/posts/show.blade.php
<x-app-layout>
    <x-slot name="header">教案詳細</x-slot>
    <x-slot name="title">教案詳細</x-slot>
    <div class="w-full pb-16">
        <div class="flex items-center justify-between mb-5">
            <h1 class="w-2/3 pl-1 text-2xl truncate lg:text-3xl lg:w-4/5">{{ $post->title }}</h1>
            {{-- 自分の投稿にはブックマークボタンを表示しない --}}
            @if ($post->user_id !== Auth::id())
            <div class="flex content-center">
                @if (Auth::check() && !Auth::user()->is_bookmarked($post->id))
                <form action="{{ route('bookmarks.store', $post) }}" method="POST" class="flex content-center">
                    @csrf
                    <button class="inline-flex items-center mr-4 text-2xl tracking-widest text-gray-500 transition duration-150 ease-in-out md:text-4xl hover:scale-95 active:scale-90">
                        <i class="fa-regular fa-bookmark"></i>
                    </button>
                </form>
                @else
                <form action="{{ route('bookmarks.destroy', $post) }}" method="POST" class="flex content-center">
                    @csrf
                    @method('DELETE')
                    <button class="inline-flex items-center mr-4 text-2xl tracking-widest transition duration-150 ease-in-out md:text-4xl hover:scale-95 active:scale-90">
                        <i class="fa-solid fa-bookmark" style="color: #fb923c;"></i>
                    </button>
                </form>
                @endif
            </div>
            @endif
        </div>
        <table class="w-full border-collapse md:text-left md:table-fixed">
            <tbody>
                <tr class="show-tr">
                    <th class="w-full show-th md:w-1/5">レベル</th>
                    <td class="w-full show-td md:w-4/5">{{ $post->level }}</td>
                </tr>
                <tr class="show-tr">
                    <th class="show-th">使用テキスト</th>
                    @if(isset($post->text->text_name))
                    <td class="show-td">{{ $post->text->text_name }}</td>
                    @else
                    <td class="show-td">&ensp;-</td>
                    @endif
                </tr>
                <tr class="show-tr">
                    <th class="show-th">投稿者</th>
                    <td class="text-blue-500 show-td hover:underline"><a href="{{ route('users.show', $post->user->id) }}">{{ $post->user->name }}</a></td>
                </tr>
                <tr class="show-tr">
                    <th class="show-th">概要</th>
                    <td class="show-td">
                        <div class="flex flex-col justify-start text-left markdown-body">
                            {!! $post->description_markdown !!}
                        </div>
                    </td>
                </tr>
                <tr class="show-tr">
                    <th class="show-th">添付ファイル</th>
                    @if(isset($post->file_name))
                    <td class="show-td">
                        <div class="flex flex-col items-center justify-center md:justify-start md:flex-row">
                            <a href="{{ $post->file_url }}" target="_blank" rel="noopener noreferrer">
                                <span class="text-blue-500 hover:underline">{{ $post->file_name }}</span>
                                @if ($post->file_mimetype === 'image/jpeg' || $post->file_mimetype === 'image/png' || $post->file_mimetype === 'application/pdf')
                                <span><i class="fa-solid fa-arrow-up-right-from-square" style="color: #3b82f6;"></i></span>
                                @endif
                            </a>
                            <div class="md:ml-6">
                                {{-- {{ 画像であれば画像を表示 }} --}}
                                @if ($post->file_mimetype === 'image/jpeg' || $post->file_mimetype === 'image/png')
                                <img src="{{ $post->file_url }}">
                                {{-- PDFであれば表示ボタンを表示 --}}
                                @elseif ($post->file_mimetype === 'application/pdf')
                                <a href="{{ $post->file_url }}" target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-center px-4 py-2 mt-2 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-blue-500 border border-transparent rounded-md shadow-md hover:bg-blue-300 focus:bg-blue-500 active:bg-blue-300 focus:outline-none md:mt-0">
                                    <span><i class="mr-2 fa-solid fa-arrow-up-right-from-square" style="color: #ffffff;"></i></span>
                                    <span>表示</span>
                                </a>
                                @else
                                <a href="{{ $post->file_url }}" download class="inline-flex items-center justify-center px-4 py-2 mt-2 text-xs font-semibold tracking-widest text-white uppercase transition duration-150 ease-in-out bg-blue-500 border border-transparent rounded-md shadow-md hover:bg-blue-300 focus:bg-blue-500 active:bg-blue-300 focus:outline-none md:mt-0">
                                    <span><i class="mr-2 fa-solid fa-download" style="color: #ffffff;"></i></span>
                                    <span>ダウンロード</span>
                                @endif
                                </a>
                            </div>
                        </div>
                    </td>
                    @else
                    <td class="show-td">&ensp;-</td>
                    @endif
                </tr>
                <tr class="show-tr">
                    <th class="show-th">ファイルサイズ</th>
                    @if(isset($post->file_size))
                    <td class="show-td">{{ $post->file_size }}</td>
                    @else
                    <td class="show-td">&ensp;-</td>
                    @endif
                </tr>
                <tr class="show-tr">
                    <th class="show-th">MIMEタイプ</th>
                    @if(isset($post->file_mimetype))
                    <td class="show-td">{{ $post->file_mimetype }}</td>
                    @else
                    <td class="show-td">&ensp;-</td>
                    @endif
                </tr>
                <tr class="show-tr">
                    <th class="show-th">投稿日</th>
                    <td class="show-td">{{ $post->created_at->format('Y/m/d') }}</td>
                </tr>
                <tr class="show-tr">
                    <th class="md:border-b-2 show-th">更新日</th>
                    <td class="border-b-2 show-td">{{ $post->updated_at->format('Y/m/d') }}</td>
                </tr>
            </tbody>
        </table>
        @can('update', $post)
            <div class="flex justify-center my-9">
                <x-primary-button onclick="location.href='{{ route('posts.edit', $post) }}'" class="mr-12 bg-orange-400 shadow-md hover:bg-orange-300 active:bg-orange-400 focus:bg-orange-400">編集する</x-primary-button>
                <form onsubmit="return confirm('本当に削除しますか？')" action="{{ route('posts.destroy', $post) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <x-primary-button class="bg-red-500 shadow-md hover:bg-red-300 active:bg-red-500 focus:bg-red-500">削除する</x-primary-button>
                </form>
            </div>
        @endcan
    </div>
</x-app-layout>