routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\MyPostController;
use App\Http\Controllers\BookmarkController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/page/terms', [PageController::class, 'terms'])->name('page.terms');
Route::get('/page/policy', [PageController::class, 'policy'])->name('page.policy');
Route::get('/page/contact', [PageController::class, 'contact'])->name('page.contact');

Route::middleware('auth')->group(function () {
    Route::resource('/posts', PostController::class)->except('index');
    Route::get('/myposts', [MyPostController::class, 'index'])->name('myposts.index');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::delete('/posts/{post}/unbookmark', [BookmarkController::class, 'destroy'])->name('bookmarks.destroy');
    Route::post('/posts/{post}/bookmark', [BookmarkController::class, 'store'])->name('bookmarks.store');
    Route::get('/bookmarks', [PostController::class, 'bookmark_posts'])->name('bookmarks');
});

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');
Route::resource('/users', UserController::class)->only(['index', 'show']);

require __DIR__.'/auth.php';

app/View/Components/PageLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class PageLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.page');
    }
}

resources/views/page/contact.blade.php
<x-page-layout>
    <x-slot name="header">お問い合わせ</x-slot>
    <x-slot name="title">お問い合わせ</x-slot>
    <div class="flex justify-center w-full">
        <div>
            <p>いつも{{ config('app.name') }}をご利用いただきありがとうございます。</p>
            <p>本サービス内において、ご意見、ご要望、バグ報告等ございましたら下記TwitterアカウントのDMにてご報告いただけますと幸いです。</p>
            <div class="text-center">
                <img src="{{ asset('images/datemaki_logo2.png') }}" alt="ロゴ" width="300" height="300" class="inline-block">
            </div>
            <div class="my-5 text-center">
                <button class="inline-flex items-center px-4 py-2 text-xs font-semibold tracking-widest text-orange-400 uppercase transition duration-150 ease-in-out border border-gray-300 rounded-md shadow-sm hover:text-orange-300 hover:border-gray-200 focus:text-orange-300 active:border-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 hover:scale-95 active:scale-90">
                    <a href="https://twitter.com/Mnsr_3" target="_blank" rel="noopener noreferrer">
                        <span><i class="fa-solid fa-envelope"></i></span>
                        <span>メッセージ</span>
                    </a>
                </button>
            </div>
        </div>
    </div>
</x-page-layout>

resources/views/page/policy.blade.php
<x-page-layout>
    <x-slot name="header">プライバシーポリシー</x-slot>
    <x-slot name="title">プライバシーポリシー</x-slot>
    <div class="flex justify-center w-full">
        <div>
            <div class="text-base">
                <p class="text-base">{{ config('app.name') }}（以下,「本サービス」といいます。）における、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>
            </div>
            <br>
            <div>
                <h2>■第一条&nbsp;個人情報</h2>
                <br>
                <p class="text-base">本サービスが「個人情報」として取り扱うのは、氏名、住所、電話番号、メールアドレス、その他の特定の個人を識別できる情報を指します。</p>
                <br>
            </div>
            <div>
                <h2>■第二条&nbsp;個人情報を収集・利用する目的</h2>
                <br>
                <div class="text-base">
                    <p>本サービスは以下の目的のために、必要な範囲内で個人情報を収集し、利用します。</p>
                    <ul>
                        <li>・本サービスの提供および運営に必要な範囲での利用</li>
                        <li>・本サービスに関するお問い合わせへの対応</li>
                        <li>・運営者からのご案内、お知らせ等の送付</li>
                    </ul>
                </div>
                <br>
            </div>
            <div>
                <h2>■第三条&nbsp;利用目的の変更</h2>
                <br>
                <div class="text-base">
                    <ul>
                        <li>１．本サービスは、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。</li>
                        <li>２．利用目的の変更を行った場合には、変更後の目的について、当方所定の方法により、本サービス上に公表するものとします。</li>
                    </ul>
                </div>
                <br>
            </div>
            <div>
                <h2>■第四条&nbsp;個人情報の第三者提供</h2>
                <br>
                <div class="text-base">
                    <p>１．運営者は、法令に基づく場合を除き、事前に本人の同意を得ることなく、収集した個人情報を第三者に提供することはありません。ただし、以下の場合にはこの限りではありません。</p>
                    <ul>
                        <li>（１）法令に基づく場合</li>
                        <li>（２）人の生命、身体または財産の保護のために必要がある場合であり、本人の同意を得ることが困難である場合</li>
                        <li>（３）国の機関または地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であり、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがある場合</li>
                    </ul>
                    <br>
                    <p>２．前項の定めにかかわらず、以下の場合は、提携する企業等への提供が行われることがあります。</p>
                    <ul>
                        <li>（１）運営者が取り扱うサービスを提供するために、提携する企業等へ必要な範囲で提供する場合</li>
                        <li>（２）運営者が取り扱うサービスにおいて、ユーザーに対する情報提供、プロモーション等を行うために、提携する企業等へ提供する場合</li>
                    </ul>
                </div>
                <br>
            </div>
            <div>
                <h2>■第五条&nbsp;個人情報の訂正および削除</h2>
                <br>
                <div class="text-base">
                    <ul>
                        <li>１．ユーザーは、運営者が保有する自己の個人情報が誤った情報である場合には、運営者が定める手続きにより、運営者に対して個人情報の訂正を請求することができます。</li>
                        <li>２．運営者は、ユーザーから個人情報の訂正または削除の請求があった場合、合理的な期間内に調査を行い、必要な範囲内で速やかに個人情報の訂正または削除を行うものとします。</li>
                    </ul>
                </div>
                <br>
            </div>
            <div>
                <h2>■第六条&nbsp;個人情報の利用停止等</h2>
                <br>
                <p class="text-base">本サービスの運営者は、ご本人からの求めにより、ご本人の個人情報の利用停止または消去を行うことができるものとします。ただし、運営者は、法令に基づく場合や正当な理由がある場合を除き、速やかに対応いたします。</p>
                <br>
            </div>
            <div>
                <h2>■第七条&nbsp;プライバシーポリシーの変更</h2>
                <br>
                <p class="text-base">本サービスの運営者は、必要に応じて、本ポリシーを変更することがあります。変更後の本ポリシーについては、本サービスのプライバシーポリシーに掲載した時点より効力を生じるものとします。</p>
                <br>
            </div>
        </div>
    </div>
</x-page-layout>

resources/views/page/terms.blade.php
<x-page-layout>
    <x-slot name="header">利用規約</x-slot>
    <x-slot name="title">利用規約</x-slot>
    <div class="flex justify-center w-full">
        <div>
            <div>
                <h2>■第一条&nbsp;定義</h2>
                <br>
                <p class="text-base">本規約は、{{ config('app.name') }}（以下、「本サービス」といいます。）のご利用条件を定めたものです。本サービスをご利用になる方（以下「会員」）は、本規約を必ずお読みのうえ、ご同意ください。なお、会員登録が完了した時点で本規約に同意したものとみなします。同意なき場合には本サービスをご利用いただくことができませんので、予めご了承ください。</p>
                <br>
            </div>
            <div>
                <h2>■第二条&nbsp;会員登録について</h2>
                <br>
                <ul class="text-base">
                    <li>１．会員登録には、本規約に同意していただく必要があります。</li>
                    <li>２．登録情報に変更が生じた場合は、速やかに運営者に通知していただく必要があります。</li>
                    <li>３．登録情報の管理は、会員自身が行うものとします。</li>
                    <li>４．登録情報が虚偽のものであったり、第三者の登録情報を使用していた場合、運営者は会員の資格を取り消すことができます。</li>
                </ul>
                <br>
            </div>
            <div>
                <h2>■第三条&nbsp;自己責任</h2>
                <br>
                <ul class="text-base">
                    <li>１．運営者は、会員が本サービスを利用したことにより生じた一切の損害について責任を負いません。</li>
                    <li>２．会員は、自己の責任において本サービスを利用するものとし、運営者は会員が本サービスを利用したことにより、直接的・間接的な損害、損失、費用、責任および請求について、一切責任を負わないものとします。</li>
                    <li>３．会員が第三者の著作権、商標権、プライバシー権等の権利を侵害した場合、会員自身がその責任を負うものとし、運営者は一切責任を負わないものとします。</li>
                    <li>４．会員が本サービスに関連して、法令に反する行為を行った場合、会員自身がその責任を負うものとし、運営者は一切責任を負わないものとします。</li>
                </ul>
                <br>
            </div>
            <div>
                <h2>■第四条&nbsp;データの管理</h2>
                <br>
                <ul class="text-base">
                    <li>１．運営者は、会員が提供する情報を適切に管理することに努めます。</li>
                    <li>２．会員は、自己の責任において、本サービスを利用することとします。また、会員は、自己のデータが漏洩した場合には、自己の責任で対応するものとします。</li>
                    <li>３．本サービス上のシステムにおいて本件情報等のデータ（以下「データ」）が完全に保存されない場合があることを会員は承諾します</li>
                    <li>４．運営者は、会員が提供する情報を、運営者が提供するサービスの改善や広告配信などの目的で利用することができます。</li>
                </ul>
                <br>
            </div>
            <div>
                <h2>■第五条&nbsp;著作権の範囲</h2>
                <br>
                <ul class="text-base">
                    <li>１．本件情報等の著作権は、作成した会員に帰属します。</li>
                    <li>２．ただし、会員は、本件情報等が会員への事前の通知または承諾を要せず、運営者または運営者が指定する者により改変（トリミング、サイズの変更、データ形式の変換行為を含みます）や複製などの利用がされる場合があることをあらかじめ承諾するものとします。</li>
                    <li>３．運営者または運営者が指定する者、他の会員により二次利用される場合があることをあらかじめ承諾するものとします。</li>
                    <li>４．会員が本サービスを利用する際に、第三者の著作物を利用する場合は、当該会員がその著作物に関する一切の責任を負うものとします。</li>
                    <li>５．会員は、本サービスを利用する際に、第三者の著作権を侵害しないように十分に注意することとします。</li>
                </ul>
                <br>
            </div>
            <div>
                <h2>■第六条&nbsp;禁止事項</h2>
                <br>
                <div class="text-base">
                    <p>１．会員は、本サービスを通じて、以下に定める禁止事項に該当するまたは該当するおそれがある行為を行ってはならないものとします。</p>
                    <br>
                    <ul>
                        <li>（１）法令に違反する行為や犯罪行為を助長する行為</li>
                        <li>（２）わいせつ、児童ポルノ、差別的、人種差別的、暴力的、過激な内容を掲載する行為</li>
                        <li>（３）他のユーザーのプライバシーや肖像権を侵害する行為</li>
                        <li>（４）虚偽の情報を投稿する行為</li>
                        <li>（５）特定の個人や団体を中傷する行為</li>
                        <li>（６）営利目的での利用や営業活動をする行為</li>
                        <li>（７）他のユーザーに対する嫌がらせ、ストーキングなどの行為</li>
                        <li>（８）運営者または第三者になりすまして利用する行為</li>
                        <li>（９）有害なプログラムやウイルス、スパムなどを配信する行為</li>
                        <li>（10）他のユーザーのアカウントを不正に取得する行為</li>
                        <li>（11）個人情報を不正に収集する行為</li>
                        <li>（12）不適切な方法で広告や宣伝をする行為</li>
                        <li>（13）著作権、商標権、特許権、意匠権などの知的財産権を侵害する行為</li>
                        <li>（14）他のユーザーに対して危害を加える行為、または加担する行為</li>
                        <li>（15）不正なゲームやくじの提供や参加をする行為</li>
                        <li>（16）運営者が提供するサービスの運営に支障をきたす行為</li>
                        <li>（17）誹謗中傷、デマなどの不正確な情報を拡散する行為</li>
                        <li>（18）禁止された行為についての助長・誘発、またはその他の支援行為</li>
                        <li>（19）運営者が不適切と判断する行為</li>
                        <li>（20）上記の禁止事項に反する行為</li>
                    </ul>
                    <br>
                    <p>２．運営者は、会員が本サービスを通じて行った本件情報等の発信または提供が、前項で定める禁止事項のいずれかに該当し、もしくは該当するおそれがある場合、またはその他の理由で不適当であると判断した場合、会員への事前の通知または承諾を要せず、以下の措置を行うことができるものとします。</p>
                    <br>
                    <ul>
                        <li>（１）当該本件情報等の本サービス上からの削除</li>
                        <li>（２）会員による本サービスの利用の停止</li>
                    </ul>
                </div>
                <br>
            </div>
            <div>
                <h2>■第七条&nbsp;本サービスの中断</h2>
                <br>
                <div class="text-base">
                    <p>１．運営者は、以下の場合には、事前の通知を行うことなく、本サービスの一時的な中断、停止、または廃止を行うことができます。</p>
                    <br>
                    <ul>
                        <li>（１）保守を定期的または緊急に行う場合</li>
                        <li>（２）火災、停電等により、本サービスの提供ができなくなった場合</li>
                        <li>（３）地震、噴火、洪水、津波等の天災により本サービスの提供ができなくなった場合</li>
                        <li>（４）戦争、変乱、暴動、騒乱、労働争議等により本サービスの提供ができなくなった場合</li>
                        <li>（５）その他、運用上、技術上、運営者が本サービスの一時的中断を必要と判断した場合</li>
                    </ul>
                    <br>
                    <p>２．前項に基づき、運営者が本サービスの一時的な中断、停止、または廃止を行った場合には、運営者はこれに関し、ユーザーに対して一切の責任を負わないものとします。</p>
                    <p>３．運営者は、本サービスの一時的な中断、停止、または廃止により、ユーザーに生じた一切の損害について、一切の責任を負わないものとします。</p>
                    <p>４．運営者は、本サービスの一時的な中断、停止、または廃止が発生した場合において、ユーザーに対して事後的に通知する場合があります。ただし、緊急を要する場合には、事前の通知を行うことなく、本サービスの一時的な中断、停止、または廃止を行うことがあります。</p>
                </div>
                <br>
            </div>
            <div>
                <h2>■第八条&nbsp;本サービスの終了</h2>
                <br>
                <div class="text-base">
                    <p>運営者は、以下の場合に会員への事前の通知または承諾を要せず、本サービスに発信または提供された本件情報等の全部または一部の削除ならびに本サービスの一部または全てを終了することができます。</p>
                    <br>
                    <ul>
                        <li>１．システム保守などのため、運営者が必要と判断した場合</li>
                        <li>２．自然災害、テロ、戦争、暴動、労働争議、電力供給の停止など、やむを得ない事由により本サービスの提供が困難または不能となった場合</li>
                        <li>３．法令等に基づく場合</li>
                    </ul>
                    <br>
                    <p>運営者は、本サービスの提供の中断または終了により、ユーザーが被った損害について何ら責任を負わないものとします。</p>
                </div>
                <br>
            </div>
            <div>
                <h2>■第九条&nbsp;本規約の変更</h2>
                <br>
                <p class="text-base">運営者は、必要に応じて本規約を変更することができます。変更後の本規約は、本サービスで掲示した時点から効力を生じるものとします。会員は、本規約の変更後も本サービスを利用することにより、変更後の本規約に同意したものとみなされます。</p>
                <br>
            </div>
            <div>
                <h2>■第十条&nbsp;免責事項</h2>
                <br>
                <div class="text-base">
                    <p>１．運営者は、以下のいずれかの事由が発生した場合、本サービスの提供を一時中断または停止することがあります。</p>
                    <br>
                    <ul>
                        <li>（１）本サービスに関するシステムの保守点検、更新、障害対応等を行う場合</li>
                        <li>（２）天災、火災、停電、第三者の妨害行為、その他運営者が合理的な理由により本サービスの提供が困難と判断した場合</li>
                    </ul>
                    <br>
                    <p>２．運営者は、本サービスにおいて提供される情報、コンテンツ、サービス等が、ユーザーに適用可能であること、完全であること、正確であること、特定の目的に適合すること、安全であること、エラーが修正されること、不具合が修復されること、または本サービスまたはサーバーから送信される電子メール等がウイルスまたはその他有害な要素を含まないことについて、いかなる保証も行いません。</p>
                    <p>３．運営者は、ユーザーが本サービスを利用したことによって生じた、直接的または間接的な損害、不利益、トラブル、クレーム、損失、費用、損害賠償等について、一切責任を負わないものとします。</p>
                    <p>４．運営者は、本サービスに関連してユーザーが提供した情報について、完全性、正確性、適法性、安全性、有用性等について、いかなる保証も行いません。ユーザーが本サービスに提供する情報については、自己の責任において提供するものとし、運営者はこれを承諾します。</p>
                    <p>５．運営者は、本サービスにおいて、ユーザーが利用したことにより発生した、第三者のクレーム、トラブル、損失、損害等について、一切責任を負わないものとします。</p>
                    <p>６．運営者は、本サービスに掲載する情報やコンテンツについて、著作権、商標権、特許権、ノウハウ、意匠権、その他一切の知的財産権を有することがあるものの、これらの権利に基づく一切の責任を負わないものとします。</p>
                    <p>７．ユーザーが本サービスに投稿した情報やコンテンツについて、第三者から著作権、プライバシー権、肖像権等の権利侵害に関するクレームがあった場合、ユーザー自身が直接的かつ全面的に責任を負うものとし、運営者はこれに関連する一切の責任を負わないものとします。</p>
                    <br>
                    <p>以上の免責事項は、運営者の過失に基づく損害賠償責任についても適用されるものとします。</p>
                </div>
                <br>
            </div>
            <div>
                <h2>■第十一条&nbsp;管轄裁判所及び準拠法</h2>
                <br>
                <p class="text-base">本規約の解釈においては日本国法が適用されるものとし、会員と運営者の間で訴訟の必要が生じた場合、【東京地方裁判所】を第一審の専属的合意管轄裁判所とします。</p>
                <br>
            </div>
        </div>
    </div>
</x-page-layout>